# Configuração do Alertmanager para testnet Holesky
# Este arquivo configura as notificações de alerta para desenvolvimento/teste

global:
  # Configurações globais para testnet
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@holesky-testnet.local'
  
# Configuração de roteamento para testnet
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'testnet-alerts'
  routes:
    # Alertas críticos para desenvolvimento
    - match:
        severity: critical
      receiver: 'critical-testnet'
      repeat_interval: 1h
    
    # Alertas de warning para desenvolvimento
    - match:
        severity: warning
      receiver: 'warning-testnet'
      repeat_interval: 6h

# Configuração de receivers para testnet
receivers:
  # Receiver padrão para testnet
  - name: 'testnet-alerts'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/alerts'
        send_resolved: true
        title: 'Holesky Testnet Alert'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Job: {{ .Labels.job }}
          Network: {{ .Labels.network }}
          {{ end }}

  # Receiver para alertas críticos
  - name: 'critical-testnet'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/alerts'
        send_resolved: true
        title: 'CRITICAL: Holesky Testnet Alert'
        text: |
          🚨 CRITICAL ALERT - HOLESKY TESTNET 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Job: {{ .Labels.job }}
          Network: {{ .Labels.network }}
          Started: {{ .StartsAt }}
          {{ end }}
          
          Please check the Grafana dashboard at http://localhost:3000

  # Receiver para alertas de warning
  - name: 'warning-testnet'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/alerts'
        send_resolved: true
        title: 'WARNING: Holesky Testnet Alert'
        text: |
          ⚠️ WARNING - HOLESKY TESTNET ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Job: {{ .Labels.job }}
          Network: {{ .Labels.network }}
          {{ end }}

# Configuração de inibição para testnet
inhibit_rules:
  # Inibir alertas menores quando há alertas críticos
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

# Configuração específica para testnet:
# - Intervalos menores para desenvolvimento
# - Receivers simplificados (webhook local)
# - Sem configuração de email/Slack para testnet
# - Foco em logs e desenvolvimento

# Para habilitar o Alertmanager na testnet:
# 1. Descomente o serviço alertmanager no docker-compose-holesky.yml
# 2. Use: docker-compose -f docker-compose-holesky.yml --profile alertmanager up -d
# 3. Acesse: http://localhost:9093
