global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@rocketpool-node.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

# Configuração para logs (webhook alternativo ou integração customizada)
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:5001/alerts'
        send_resolved: true

# Exemplo de configuração para email (descomente quando configurado)
# - name: 'email-alert'
#   email_configs:
#   - to: 'admin@yourcompany.com'
#     subject: 'Rocket Pool Node Alert: {{ .GroupLabels.alertname }}'
#     body: |
#       {{ range .Alerts }}
#       Alert: {{ .Annotations.summary }}
#       Description: {{ .Annotations.description }}
#       Instance: {{ .Labels.instance }}
#       Severity: {{ .Labels.severity }}
#       {{ end }}

# Exemplo de configuração para Slack (descomente quando configurado)
# - name: 'slack-alert'
#   slack_configs:
#   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#     channel: '#alerts'
#     title: 'Rocket Pool Node Alert'
#     text: |
#       {{ range .Alerts }}
#       Alert: {{ .Annotations.summary }}
#       Description: {{ .Annotations.description }}
#       Severity: {{ .Labels.severity }}
#       {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
