global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'execution-client'
    static_configs:
      - targets: ['execution-client:6060']
    metrics_path: /debug/metrics/prometheus

  - job_name: 'consensus-client'
    static_configs:
      - targets: ['consensus-client:5054']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alerts/node-alerts.yml"
