global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'execution-client'
    static_configs:
      - targets: ['execution-client:6060']
    metrics_path: /debug/metrics/prometheus
    scrape_interval: 30s

  - job_name: 'consensus-client'
    static_configs:
      - targets: ['consensus-client:5054']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
