# Rocket Pool v1.16.0 - Configuração para Testnet Holesky
# Baseado no template oficial (user-settings.template.yml)
# Configuração mínima para Rocket Pool v1.16.0 em modo híbrido (Docker)

root:
  # Versão do Rocket Pool
  version: "1.16.0"
  
  # Rede Ethereum (holesky testnet)
  network: "testnet"
  
  # Modo Native (false = Docker mode, true = Native mode)
  isNative: false
  
  # Modo dos clientes (local/external)
  executionClientMode: external    # Cliente de execução externo (Geth)
  consensusClientMode: external    # Cliente de consenso externo (Lighthouse)

smartnode:
  network: testnet

# Configuração do cliente de execução externo
externalExecution:
  httpUrl: http://geth:8545     # HTTP RPC do Geth
  wsUrl: ws://geth:8546         # WebSocket do Geth

# Configuração do cliente de consenso externo
externalLighthouse:
  httpUrl: http://lighthouse:5052     # HTTP API do Lighthouse

# Observações para Testnet Holesky:
# - Chain ID: 17000 (diferente da mainnet que é 1)
# - ETH de teste: Disponível via faucets gratuitos
# - Comandos básicos: docker exec -it rocketpool-node-holesky rocketpool [comando]