# Rocket Pool v1.16.0 - Template de Configuração
# Este arquivo serve como template para configuração do Rocket Pool em modo híbrido
# 
# IMPORTANTE: 
# - O arquivo ativo está em /Volumes/KINGSTON/ethereum-data/rocketpool/user-settings.yml
# - Este é apenas um template de referência
# - Não edite diretamente o arquivo ativo, use este como base

# Configuração mínima para Rocket Pool v1.16.0 em modo híbrido (Docker)
root:
  # Versão do Rocket Pool
  version: "1.16.0"
  
  # Rede Ethereum (mainnet/goerli/holesky)
  network: "mainnet"
  
  # Modo Native (false = Docker mode, true = Native mode)
  isNative: "false"
  
  # Modo dos clientes (local/external)
  executionClientMode: "external"    # Cliente de execução externo (Geth)
  consensusClientMode: "external"    # Cliente de consenso externo (Lighthouse)
  
  # URLs dos clientes externos (nomes dos containers Docker)
  externalExecutionHttpUrl: "http://execution-client:8545"     # HTTP RPC do Geth
  externalExecutionWsUrl: "ws://execution-client:8546"         # WebSocket do Geth
  externalConsensusHttpUrl: "http://consensus-client:5052"     # HTTP API do Lighthouse

# Outras configurações possíveis (adicionar conforme necessário):
# - rewardsTreeMode: "download"
# - manualMaxFee: "0"
# - priorityFee: "2"
# - autoTxGasThreshold: "150"
# - enableMetrics: "true"
# - enableMevBoost: "false"
