# Rocket Pool v1.16.0 - Configuração para modo híbrido (Docker)
# Baseado no template oficial

root:
  # Versão do Rocket Pool
  version: "1.16.0"
  
  # Rede Ethereum (mainnet/goerli/holesky)
  network: "mainnet"
  
  # Modo Native (false = Docker mode, true = Native mode)
  isNative: false
  
  # Modo dos clientes (local/external)
  executionClientMode: external    # Cliente de execução externo (Geth)
  consensusClientMode: external    # Cliente de consenso externo (Lighthouse)
  
  # URLs dos clientes externos (nomes dos containers Docker)
  externalExecutionHttpUrl: http://execution-client:8545     # HTTP RPC do Geth
  externalExecutionWsUrl: ws://execution-client:8546         # WebSocket do Geth
  externalConsensusHttpUrl: http://consensus-client:5052     # HTTP API do Lighthouse

# Outras configurações
enableMevBoost: false
enableMetrics: true
